import { Agent, Bet, Game } from "@repo/db";

type LeaderboardEntry = {
  rank: number;
  name: string;
  wins: number;
  totalBets: number;
  winRate: number;
  totalEarnings: number;
};

const agents = [
  {
    id: "gpt4o",
    name: "GPT-4o",
    color: "#FFFFFF",
    createdAt: new Date(),
    wins: 0,
    avatarUrl: null,
    draws: 0,
    losses: 0,
    totalGames: 0,
    updatedAt: new Date(),
    winRate: 0.0,
  },
  {
    id: "claude",
    name: "Claude",
    color: "#C4A882",
    createdAt: new Date(),
    wins: 0,
    avatarUrl: null,
    draws: 0,
    losses: 0,
    totalGames: 0,
    updatedAt: new Date(),
    winRate: 0.0,
  },
  {
    id: "gemini",
    name: "Gemini",
    color: "#8B9DC3",
    createdAt: new Date(),
    wins: 0,
    avatarUrl: null,
    draws: 0,
    losses: 0,
    totalGames: 0,
    updatedAt: new Date(),
    winRate: 0.0,
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    color: "#7B8794",
    createdAt: new Date(),
    wins: 0,
    avatarUrl: null,
    draws: 0,
    losses: 0,
    totalGames: 0,
    updatedAt: new Date(),
    winRate: 0.0,
  },
];

export const MOCK_GAMES: (Game & { agents: Agent[] })[] = [
  {
    id: "g1",
    name: "Alpha Arena",
    status: "LIVE",
    totalPool: 43.5,
    startedAt: new Date(Date.now() - 3 * 60 * 1000),
    winnerAgentId: null,
    bettingOpensAt: new Date(Date.now() - 3 * 60 * 1000 - 10 * 60 * 1000),
    bettingClosesAt: new Date(Date.now() - 3 * 60 * 1000),
    endedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    agents: agents,
  },
  {
    id: "g2",
    name: "Beta Blitz",
    status: "UPCOMING",
    totalPool: 43.5,
    startedAt: new Date(Date.now() - 3 * 60 * 1000),
    winnerAgentId: null,
    bettingOpensAt: new Date(Date.now() - 3 * 60 * 1000 - 10 * 60 * 1000),
    bettingClosesAt: new Date(Date.now() - 3 * 60 * 1000),
    endedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    agents: agents,
  },
  {
    id: "g3",
    name: "Gamma Grid",
    status: "UPCOMING",
    totalPool: 43.5,
    startedAt: new Date(Date.now() - 3 * 60 * 1000),
    winnerAgentId: null,
    bettingOpensAt: new Date(Date.now() - 3 * 60 * 1000 - 10 * 60 * 1000),
    bettingClosesAt: new Date(Date.now() - 3 * 60 * 1000),
    endedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    agents: agents,
  },
  {
    id: "g4",
    name: "Delta Dome",
    status: "UPCOMING",
    totalPool: 43.5,
    startedAt: new Date(Date.now() - 3 * 60 * 1000),
    winnerAgentId: null,
    bettingOpensAt: new Date(Date.now() - 3 * 60 * 1000 - 10 * 60 * 1000),
    bettingClosesAt: new Date(Date.now() - 3 * 60 * 1000),
    endedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    agents: agents,
  },
  {
    id: "g5",
    name: "Sigma Storm",
    status: "UPCOMING",
    totalPool: 43.5,
    startedAt: new Date(Date.now() - 3 * 60 * 1000),
    winnerAgentId: null,
    bettingOpensAt: new Date(Date.now() - 3 * 60 * 1000 - 10 * 60 * 1000),
    bettingClosesAt: new Date(Date.now() - 3 * 60 * 1000),
    endedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    agents: agents,
  },
];

export const MOCK_BETS: Bet[] = [
  {
    id: "b1",
    gameId: "g1",
    agentId: "gpt4o",
    amount: 5.0,
    payout: 0,
    status: "PENDING",
    payoutTxHash: null,
    settledAt: null,
    txHash: "",
    userId: "",
    walletAddress: "",
    placedAt: new Date(Date.now() - 5 * 60 * 1000),
  },
  {
    id: "b2",
    gameId: "g4",
    payoutTxHash: null,
    settledAt: null,
    txHash: "",
    userId: "",
    walletAddress: "",
    agentId: "gpt4o",
    amount: 8.0,
    payout: 38.0,
    status: "WON",
    placedAt: new Date(Date.now() - 25 * 60 * 1000),
  },
  {
    id: "b3",
    gameId: "g5",
    payoutTxHash: null,
    settledAt: null,
    txHash: "",
    userId: "",
    walletAddress: "",
    agentId: "gemini",
    amount: 3.0,
    payout: 0,
    status: "LOST",
    placedAt: new Date(Date.now() - 45 * 60 * 1000),
  },
];

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  {
    rank: 1,
    name: "gpt4o",
    wins: 14,
    totalBets: 20,
    winRate: 70,
    totalEarnings: 142.5,
  },
  {
    rank: 2,
    name: "claude",
    wins: 12,
    totalBets: 18,
    winRate: 66.7,
    totalEarnings: 98.1,
  },
  {
    rank: 3,
    name: "gemini",
    wins: 11,
    totalBets: 22,
    winRate: 50,
    totalEarnings: 79.3,
  },
  {
    rank: 4,
    name: "deepseek",
    wins: 9,
    totalBets: 25,
    winRate: 36,
    totalEarnings: 48.7,
  },
  {
    rank: 5,
    name: "Agent",
    wins: 7,
    totalBets: 30,
    winRate: 23.3,
    totalEarnings: 22.4,
  },
];
