// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file game.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file game.proto.
 */
export const file_game: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CgpnYW1lLnByb3RvIh0KBVBvaW50EgkKAXgYASABKAISCQoBeRgCIAEoAiIcCgRGb29kEgkKAXgYASABKAISCQoBeRgCIAEoAiLTAQoFQWdlbnQSCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRINCgVjb2xvchgDIAEoCRIOCgZhY2NlbnQYBCABKAkSDQoFYWxpdmUYBSABKAgSDQoFc2NvcmUYBiABKA0SDAoEc2l6ZRgHIAEoAhINCgVhbmdsZRgIIAEoAhIUCgRoZWFkGAkgASgLMgYuUG9pbnQSFAoEYm9keRgKIAMoCzIGLlBvaW50Eg4KBmxlbmd0aBgLIAEoDRIRCgRyYW5rGAwgASgNSACIAQFCBwoFX3JhbmsiTQoNTGl2ZU1hdGNoVGljaxIPCgdnYW1lX2lkGAEgASgNEhMKBGZvb2QYAiADKAsyBS5Gb29kEhYKBmFnZW50cxgDIAMoCzIGLkFnZW50IjMKCE1hdGNoRW5kEg8KB2dhbWVfaWQYASABKA0SFgoGd2lubmVyGAIgASgLMgYuQWdlbnQiWgoNU2VydmVyTWVzc2FnZRIeCgR0aWNrGAEgASgLMg4uTGl2ZU1hdGNoVGlja0gAEh4KCW1hdGNoX2VuZBgCIAEoCzIJLk1hdGNoRW5kSABCCQoHcGF5bG9hZGIGcHJvdG8z",
  );

/**
 * @generated from message Point
 */
export type Point = Message<"Point"> & {
  /**
   * @generated from field: float x = 1;
   */
  x: number;

  /**
   * @generated from field: float y = 2;
   */
  y: number;
};

/**
 * Describes the message Point.
 * Use `create(PointSchema)` to create a new message.
 */
export const PointSchema: GenMessage<Point> =
  /*@__PURE__*/
  messageDesc(file_game, 0);

/**
 * @generated from message Food
 */
export type Food = Message<"Food"> & {
  /**
   * @generated from field: float x = 1;
   */
  x: number;

  /**
   * @generated from field: float y = 2;
   */
  y: number;
};

/**
 * Describes the message Food.
 * Use `create(FoodSchema)` to create a new message.
 */
export const FoodSchema: GenMessage<Food> =
  /*@__PURE__*/
  messageDesc(file_game, 1);

/**
 * @generated from message Agent
 */
export type Agent = Message<"Agent"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string color = 3;
   */
  color: string;

  /**
   * @generated from field: string accent = 4;
   */
  accent: string;

  /**
   * @generated from field: bool alive = 5;
   */
  alive: boolean;

  /**
   * @generated from field: uint32 score = 6;
   */
  score: number;

  /**
   * @generated from field: float size = 7;
   */
  size: number;

  /**
   * @generated from field: float angle = 8;
   */
  angle: number;

  /**
   * @generated from field: Point head = 9;
   */
  head?: Point | undefined;

  /**
   * @generated from field: repeated Point body = 10;
   */
  body: Point[];

  /**
   * @generated from field: uint32 length = 11;
   */
  length: number;

  /**
   * @generated from field: optional uint32 rank = 12;
   */
  rank?: number | undefined;
};

/**
 * Describes the message Agent.
 * Use `create(AgentSchema)` to create a new message.
 */
export const AgentSchema: GenMessage<Agent> =
  /*@__PURE__*/
  messageDesc(file_game, 2);

/**
 * @generated from message LiveMatchTick
 */
export type LiveMatchTick = Message<"LiveMatchTick"> & {
  /**
   * @generated from field: uint32 game_id = 1;
   */
  gameId: number;

  /**
   * @generated from field: repeated Food food = 2;
   */
  food: Food[];

  /**
   * @generated from field: repeated Agent agents = 3;
   */
  agents: Agent[];
};

/**
 * Describes the message LiveMatchTick.
 * Use `create(LiveMatchTickSchema)` to create a new message.
 */
export const LiveMatchTickSchema: GenMessage<LiveMatchTick> =
  /*@__PURE__*/
  messageDesc(file_game, 3);

/**
 * @generated from message MatchEnd
 */
export type MatchEnd = Message<"MatchEnd"> & {
  /**
   * @generated from field: uint32 game_id = 1;
   */
  gameId: number;

  /**
   * @generated from field: Agent winner = 2;
   */
  winner?: Agent | undefined;
};

/**
 * Describes the message MatchEnd.
 * Use `create(MatchEndSchema)` to create a new message.
 */
export const MatchEndSchema: GenMessage<MatchEnd> =
  /*@__PURE__*/
  messageDesc(file_game, 4);

/**
 * @generated from message ServerMessage
 */
export type ServerMessage = Message<"ServerMessage"> & {
  /**
   * @generated from oneof ServerMessage.payload
   */
  payload:
    | {
        /**
         * @generated from field: LiveMatchTick tick = 1;
         */
        value: LiveMatchTick;
        case: "tick";
      }
    | {
        /**
         * @generated from field: MatchEnd match_end = 2;
         */
        value: MatchEnd;
        case: "matchEnd";
      }
    | { case: undefined; value?: undefined };
};

/**
 * Describes the message ServerMessage.
 * Use `create(ServerMessageSchema)` to create a new message.
 */
export const ServerMessageSchema: GenMessage<ServerMessage> =
  /*@__PURE__*/
  messageDesc(file_game, 5);
